com.thoughtworks.xstream.io.StreamException: 
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:124)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:135)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.hasMoreChildren(AbstractPullReader.java:87)
	at com.intellij.database.model.serialization.FixHierarchicalStreamReader.hasMoreChildren(FixHierarchicalStream.kt)
	at com.intellij.database.model.serialization.ModelImporter.deserializeObject(ModelImporter.java:168)
	at com.intellij.database.model.serialization.ModelImporter.deserializeModel(ModelImporter.java:121)
	at com.intellij.database.model.serialization.ModelSerializerKt.deserialize(ModelSerializer.kt:25)
	at com.intellij.database.model.serialization.ModelSerializerKt.deserialize(ModelSerializer.kt:15)
	at com.intellij.database.dataSource.DataSourceStorage.readModel(DataSourceStorage.java:768)
	at com.intellij.database.dataSource.DataSourceStorage.readModel(DataSourceStorage.java:756)
	at com.intellij.database.dataSource.DataSourceStorage.loadModels(DataSourceStorage.java:561)
	at com.intellij.database.dataSource.DataSourceStorage.readStateHeavy(DataSourceStorage.java:441)
	at com.intellij.database.dataSource.DataSourceStorage$2.run(DataSourceStorage.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.xmlpull.v1.XmlPullParserException: unexpected character in markup < (position: START_TAG seen ...<root id="1">\r\n<<... @5:3) 
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1261)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
	... 30 more
